# Generated by Django 3.1.2 on 2020-10-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_test',
            field=models.CharField(default='', max_length=10),
        ),
    ]
